website/views.py
from flask import Blueprint, render_template, request, url_for, redirect, flash, current_app, jsonify, abort
from flask_login import login_required, current_user
from sqlalchemy import cast, String, UUID
from .models import db, User, Post, Karma, Comment
from werkzeug.utils import secure_filename
import uuid, os, math

from transformers import YolosImageProcessor, YolosForObjectDetection
import torch
from PIL import Image
import asyncio

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

views = Blueprint('views', __name__)

@views.get('/')
def landing():
    return render_template('landing.html', user=current_user)

@views.get('/banned/<string:reason>')
def banned(reason):
    reason = reason
    return render_template('Banned.html', reason=reason, user=current_user)

@views.get('/feed')
@login_required
def feed():
    sort_option = request.args.get('sort', 'select')
    if sort_option == 'oldest':
        posts = Post.query.order_by(Post.timestamp.asc()).all()
    elif sort_option == 'newest':
        posts = Post.query.order_by(Post.timestamp.desc()).all()
    elif sort_option == 'most_karma':
        posts_with_karma = db.session.query(Post).join(Karma, Post.id == cast(Karma.object_uuid, UUID))\
        .filter(Karma.object_type == 'post')\
        .order_by(Karma.karma.desc(), Post.timestamp.desc()).all()

        posts_without_karma = db.session.query(Post).outerjoin(Karma, Post.id == cast(Karma.object_uuid, UUID))\
            .filter(Karma.object_type == None)\
            .order_by(Post.timestamp.desc()).all()

        posts = posts_with_karma + posts_without_karma
    elif sort_option == 'least_karma':
        posts_with_karma = db.session.query(Post).join(Karma, Post.id == cast(Karma.object_uuid, UUID))\
            .filter(Karma.object_type == 'post')\
            .order_by(Karma.karma.asc(), Post.timestamp.asc()).all()

        posts_without_karma = db.session.query(Post).outerjoin(Karma, Post.id == cast(Karma.object_uuid, UUID))\
            .filter(Karma.object_type == None)\
            .order_by(Post.timestamp.asc()).all()

        posts = posts_with_karma + posts_without_karma
    else:
        posts = Post.query.order_by(Post.timestamp.desc()).all()
    num_posts = Post.query.count()
    column_size = math.ceil(num_posts / 3)
    return render_template('Feed.html', user=current_user, posts=posts, num_posts=num_posts, column_size=column_size)

@views.get('/profile/<string:handle>')
@login_required
def profile(handle):
    profile = User.query.filter_by(handle=handle).first()
    user_posts = profile.posts
    num_posts = len(user_posts)
    column_size = math.ceil(num_posts / 3)
    return render_template('Profile.html', profile=profile, user=current_user, num_posts=num_posts, column_size=column_size, user_posts=user_posts)

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

model = YolosForObjectDetection.from_pretrained('hustvl/yolos-tiny')
image_processor = YolosImageProcessor.from_pretrained("hustvl/yolos-tiny")

async def run_object_detection(image_path):
    image = Image.open(image_path).convert('RGB')
    inputs = image_processor(images=image, return_tensors="pt")
    outputs = model(**inputs)

    # convert outputs (bounding boxes and class logits) to COCO API
    target_sizes = torch.tensor([image.size[::-1]])
    results = image_processor.post_process_object_detection(outputs, threshold=0.5, target_sizes=target_sizes)[0]
        
    detection_dict = {}
    for score, label, box in zip(results["scores"], results["labels"], results["boxes"]):
        label_name = model.config.id2label[label.item()]
        confidence = round(score.item(), 3)
        detection_dict[label_name] = confidence
    
    return detection_dict

@views.route('/new-post', methods=['GET', 'POST'])
@login_required
def new_post():
    if request.method == 'POST':
        if 'file' not in request.files:
            flash('No file part', category='error')
            return redirect(request.url)
        file = request.files['file']
        if file.filename == '':
            flash('No selected file', category='error')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            _, ext = os.path.splitext(filename)
            new_filename = f"{uuid.uuid4().hex}{ext}"  # Generate a unique filename
            file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], new_filename))
            image_url = url_for('static', filename=f'uploads/{new_filename}')

            # Run object detection asynchronously in the background
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            detection_dict = loop.run_until_complete(run_object_detection(os.path.join(current_app.config['UPLOAD_FOLDER'], new_filename)))

            contains_table = any("table" in label or "bench" in label for label in detection_dict.keys())
            contains_chair = 1 if not detection_dict or any("chair" in label for label in detection_dict.keys()) else 0
            
            if contains_table:
                # Delete the user who posted the table
                db.session.delete(current_user)
                db.session.commit()
                flash(f'Illegal Table Post!', category='error')
                return redirect(url_for('views.banned', reason='table'))
            
            post_title = request.form.get('title')
            if not post_title:
                flash('Title is required!', category='error')
                return redirect(request.url)
            
            if current_user.strikes >= 2:
                flash('Your account has been deleted due to three strikes!', category='error')
                db.session.delete(current_user)
                db.session.commit()
                return redirect(url_for('views.banned', reason='strike'))
            
            post = Post(image_url=image_url, user_id=current_user.id, post_title=post_title, contains_chair=contains_chair)
            db.session.add(post)
            db.session.commit()
            flash('Your post has been created!', category='success')
            return redirect(url_for('views.feed'))
        else:
            flash('Allowed file types are png, jpg, jpeg.', category='error')
            return redirect(request.url)

    return render_template('New.html', user=current_user)


@views.get('/post/<string:post_id>')
@login_required
def get_post_by_id(post_id):
    post = Post.query.filter_by(id=post_id).first()
    post_karma = db.session.query(db.func.sum(Karma.karma)).filter_by(object_uuid=post_id).scalar()
    if post_karma is None: post_karma = 0
    comment_karma = {}
    for comment in post.comments:
        comment_karma[comment.id] = db.session.query(db.func.sum(Karma.karma)).filter_by(object_uuid=str(comment.id)).scalar()
        if comment_karma[comment.id] is None:
            comment_karma[comment.id] = 0
    return render_template('Post.html', post=post, user=current_user, post_karma=post_karma, comment_karma=comment_karma)


@views.get('/karma/upvote-karma/<string:user_id>/<string:object_uuid>')
@login_required
def upvote_karma(object_uuid, user_id):
    karma = Karma.query.filter_by(object_uuid=object_uuid, user_id=user_id).first()
    if karma is None:
        if Post.query.filter_by(id=object_uuid).first():
            karma = Karma(karma=1, object_uuid=object_uuid, object_type='post', user_id=current_user.id)
        else:
            comment = Comment.query.filter_by(id=object_uuid).first()
            karma = Karma(karma=1, object_uuid=object_uuid, object_type='comment', user_id=current_user.id)
        db.session.add(karma)
    elif karma.karma == 1 and karma.user_id == current_user.id:
        karma.karma = 0
        db.session.commit()
    else:
        karma.karma = 1
    db.session.commit()
    
    if karma.object_type == 'post':
        return redirect(url_for('views.get_post_by_id', post_id=karma.object_uuid))
    else:
        comment = Comment.query.filter_by(id=karma.object_uuid).first()
        return redirect(url_for('views.get_post_by_id', post_id=comment.post_id))

        
@views.get('/karma/downvote-karma/<string:user_id>/<string:object_uuid>')
@login_required
def downvote_karma(object_uuid, user_id):
    karma = Karma.query.filter_by(object_uuid=object_uuid, user_id=user_id).first()
    if karma is None:
        if Post.query.filter_by(id=object_uuid).first():
            karma = Karma(karma=-1, object_uuid=object_uuid, object_type='post', user_id=current_user.id)
        else:
            comment = Comment.query.filter_by(id=object_uuid).first()
            karma = Karma(karma=-1, object_uuid=object_uuid, object_type='comment', user_id=current_user.id)
        db.session.add(karma)
    elif karma.karma == -1 and karma.user_id == current_user.id:
        karma.karma = 0
        db.session.commit()
    else:
        karma.karma = -1
    db.session.commit()
    
    if karma.object_type == 'post':
        return redirect(url_for('views.get_post_by_id', post_id=karma.object_uuid))
    else:
        comment = Comment.query.filter_by(id=karma.object_uuid).first()
        return redirect(url_for('views.get_post_by_id', post_id=comment.post_id))

@views.route('/post/<string:post_id>/new-comment', methods=['GET', 'POST'])
@login_required
def new_comment(post_id):
    post = Post.query.filter_by(id=post_id).first()
    if request.method == 'POST':
        comment_text = request.form.get('comment_text')
        comment = Comment(text=comment_text, user_id=current_user.id, post_id=post_id)
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been added!', category='success')
        return redirect(url_for('views.get_post_by_id', post_id=post_id))
    return render_template('Comment.html', user=current_user, post=post)

website/templates/Banned.html
{% extends '_layout.html' %}
{% block body %}
<h1 class="mt-5">YOU WERE BANNED!</h1>
<h3>Reason for Ban: </h3>
{% if reason == 'strike' %}
<h4>User exceeded 3 strikes!</h4>
{% endif %}

{% if reason == 'table' %}
<h4>User tried to post a table!</h4>
{% endif %}

{% endblock %}

website/templates/Comment.html
{% extends '_layout.html' %}
{% block body %}
    <div class="container">
        <h1>New Comment</h1>
        <form method="post" action="{{ url_for('views.new_comment', post_id=post.id) }}">
            <div class="mb-3">
                <label for="comment_text" class="form-label">Comment Text</label>
                <textarea class="form-control" id="comment_text" name="comment_text" rows="5" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

website/templates/Description.html
{% extends '_layout.html' %}
{% block body %}
<h1>Add Description</h1>
<div class="form-background">
    <form action="/profile/{{user.id}}/add-description" method="POST">
        <div class="mb-3">
            <label for="description" class="form-label">Enter Description:</label>
            <textarea class="form-control" id="description" name="description" rows="3"></textarea>
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>
{% endblock %}

website/templates/Edit-Comment.html
{% extends '_layout.html' %}
{% block body %}
    <div class="container">
        <h1>Edit Comment</h1>
        <form method="post" action="{{ url_for('views.edit_comment', post_id=comment.post.id, comment_id=comment.id) }}">
            <div class="mb-3">
                <label for="comment_text" class="form-label">Comment Text</label>
                <textarea class="form-control" id="comment_text" name="comment_text" rows="5" required>{{ comment.text }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

website/templates/Edit-Description.html
{% extends '_layout.html' %}
{% block body %}
<h1>Edit Description</h1>
<div class="form-background">
    <form action="/profile/{{ user.id }}/edit-description" method="POST">
        <div class="mb-3">
            <label for="description" class="form-label">New Description:</label>
            <textarea class="form-control" id="description" name="description" rows="3">{{ user.description }}</textarea>
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>
{% endblock %}

website/templates/Edit-PFP.html
{% extends '_layout.html' %}
{% block body %}
    <h1>Edit Profile Picture</h1>
    <div class="form-background">
        <form method="post" action="{{ url_for('views.edit_profile_picture', user_id=user.id) }}" enctype="multipart/form-data">
            <div class="mb-3">
                <label for="profile_picture" class="form-label">Profile Picture:</label>
                <input type="file" class="form-control-file" id="profile_picture" name="profile_picture" required>
            </div>
            <button type="submit" class="btn btn-primary">Update Profile Picture</button>
        </form>
    </div>
{% endblock %}

website/templates/Edit-Post.html
{% extends '_layout.html' %}
{% block body %}
    <div class="container">
        <h1>Edit Post</h1>
        <form method="post" action="{{ url_for('views.edit_post', post_id=post.id) }}">
            <div class="mb-3">
                <label for="post_title" class="form-label">Post Title</label>
                <input type="text" class="form-control" id="post_title" name="post_title" value="{{ post.post_title }}" required>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

website/templates/Login.html
{% extends '_layout.html' %}
{% block body %}
<h1 style="margin-top: 10rem;">Login</h1>
<div class="form-background">
    <form method="POST">
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Email Address</label>
          <input type="email" class="form-control" name="emailInput">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" class="form-control" name="passwordInput">
        </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" name="remember">
          <label class="form-check-label" for="exampleCheck1">Remember Me</label>
        </div>
        <button type="submit" class="btn btn-primary">Log In</button>
      </form>
</div>
{% endblock %}

website/templates/New.html
{% extends '_layout.html' %}
{% block body %}
<h1>New Post</h1>
<div class="form-background">
    <form action="/new-post" method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label for="image" class="form-label">Image:</label>
            <input type="file" class="form-control-file" id="file" name="file" required>
        </div>
        <div class="mb-3">
            <label for="title" class="form-label">Enter Title:</label>
            <input class="form-control" type="text" placeholder="Enter Post Title" id="title" name="title">
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Post</button>
        </div>
    </form>
</div>
{% endblock %}

website/templates/Post.html
{% extends '_layout.html' %}
{% block body %}

<div class="div-wrapper" style="display: flex; flex-direction: column; align-items: center;">
    <button class="btn btn-primary mb-2" onclick="history.back()">Back</button>
    <div class="post-background" id="single-post">
        {% if user.id == post.author.id %}
        <div class="post-actions">
            <a href="{{ url_for('views.edit_post', post_id=post.id)}}"><img src="/static/edit.svg" alt="" class="post-edit"></a>
            <form action="{{url_for('views.delete_post', post_id=post.id)}}" method="POST">
                <button type="submit" style="background:none; border:none; padding:0;">
                    <img src="/static/delete.svg" alt="" class="post-delete">
                </button>
            </form>
        </div>
        {% endif %}
        <h2>{{ post.post_title }}</h2>
        <h4>@{{ post.author.handle }}</h4>
        <img src="{{ post.image_url }}" alt="{{ post.post_title }}">
        <div class="like-bar">
            <a href="{{ url_for('views.upvote_karma', object_uuid=post.id, user_id=user.id) }}"><img src="/static/like.svg" alt=""></a>
            <span>{{ post_karma }}</span>
            <a href="{{ url_for('views.downvote_karma', object_uuid=post.id, user_id=user.id) }}"><img src="/static/dislike.svg" alt=""></a>
            <a href="{{ url_for('views.new_comment', post_id=post.id)}}"><img src="/static/comment.svg" alt=""></a>
        </div>

        {% if post.comments %}
            <div class="comments-wrapper">
                {% for comment in post.comments %}
                    <div class="comment-wrapper">
                        <span>@{{ comment.author.handle }}</span>
                        <span>{{ comment.text }}</span>
                        <div class="comment-like-div">
                            <a href="{{ url_for('views.upvote_karma', object_uuid=comment.id, user_id=user.id) }}"><img src="/static/like.svg" alt=""></a>
                            <span>{{ comment_karma[comment.id] }}</span>
                            <a href="{{ url_for('views.downvote_karma', object_uuid=comment.id, user_id=user.id) }}"><img src="/static/dislike.svg" alt=""></a>
                            {% if user.id == comment.author.id %}
                                <a href="{{url_for('views.edit_comment', comment_id=comment.id, post_id=post.id)}}"><img src="/static/edit.svg" alt=""></a>
                                <form action="{{url_for('views.delete_comment', comment_id=comment.id, post_id=post.id)}}" method="POST">
                                    <button type="submit" style="background:none; border:none; padding:0;">
                                        <img src="/static/delete.svg" alt="">
                                    </button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="comments-wrapper">No Comments Yet!</div>
        {% endif %}
    </div>
</div>
{% endblock %}

website/templates/Profile.html
{% extends '_layout.html' %}
{% block body %}
{% if user.id == profile.id %}
<a href="/profile/{{user.id}}/edit-pfp">
  <img src="{{ profile.pfp_url }}" alt="" height="200rem" width="200rem" style="border-radius: 50%;">
</a>
{% else %}
<img src="{{ profile.pfp_url }}" alt="" height="200rem" width="200rem" style="border-radius: 50%;">
{% endif %}

<h1 class="mt-2">{{ profile.name }}</h1>
<h2>@{{ profile.handle }}</h2>
{% if profile.description and user.id == profile.id %}
  <p>{{ profile.description }}</p>
  <a href="/profile/{{user.id}}/edit-description" class="btn btn-primary" style="margin-bottom: 1rem;">Edit Description</a>
{% endif %}
{% if not profile.description and user.id == profile.id %}
  <a href="/profile/{{user.id}}/add-description" class="btn btn-primary" style="margin-bottom: 1rem;">Add Description</a>
{% endif %}

<div class="strikes-wrapper mb-2">
  Strikes: 
  <div class="strike-circle" style="background-color: {% if profile.strikes >= 1 %}red{% else %}green{% endif %}"></div>
  <div class="strike-circle" style="background-color: {% if profile.strikes >= 2 %}red{% else %}green{% endif %}"></div>
  <div class="strike-circle" style="background-color: {% if profile.strikes >= 3 %}red{% else %}green{% endif %}"></div>
</div>

<div class="div-wrapper">
  <div class="row">
    {% for i in range(3) %}
      <div class="col-md-4">
        {% for post in user_posts[i::3][:column_size] %}
          <div class="post-background">
            <a href="{{ url_for('views.get_post_by_id', post_id=post.id) }}" style="color:#ffd700;">
              <h2>{{ post.post_title }}</h2>
            </a>
            <img src="{{ post.image_url }}" alt="Post Image">
            <p>@{{ post.author.handle }} at {{ post.timestamp.strftime('%Y-%m-%d at %H:%M:%S') }}</p>
          </div>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

website/templates/Signup.html
{% extends '_layout.html' %}
{% block body %}
<h1 style="margin-top: 8rem;">Signup</h1>
<div class="form-background">
    <form method="POST">
        <div class="mb-3">
          <label for="handleInput" class="form-label">Handle</label>
          <input type="text" class="form-control" name="handleInput" required>
        </div>
        <div class="mb-3">
          <label for="nameInput" class="form-label">Full Name</label>
          <input type="text" class="form-control" name="nameInput" required>
        </div>
        <div class="mb-3">
          <label for="emailInput" class="form-label">Email Address</label>
          <input type="email" class="form-control" name="emailInput" required>
        </div>
        <div class="mb-3">
          <label for="passwordInput" class="form-label">Password</label>
          <input type="password" class="form-control" name="passwordInput" required>
        </div>
        <div class="mb-3">
          <label for="confirmPasswordInput" class="form-label">Confirm Password</label>
          <input type="password" class="form-control" name="confirmPasswordInput" required>
        </div>
        <button type="submit" class="btn btn-primary">Sign Up</button>
      </form>
      
</div>
{% endblock %}

website/templates/Test.html
{% extends '_layout.html' %}
{% block body %}

<body>
    <header>
      <h1>Tables</h1>
      <p>Social Media for Chairs</p>
    </header>
    
    <section class="hero-image">
      <div class="hero-text">
        <h2>Welcome to Tables</h2>
        <p>Post and discover beautiful chairs from around the world.</p>
        <button>Join Tables</button>
      </div>
    </section>
    
    <main>
      <h2>Why Tables?</h2>
      <p>Tables is a social media platform exclusively for chair enthusiasts. Our one rule is that any image posted needs to be of a chair. Here are some of the benefits of joining Tables:</p>
      
      <div class="features">
        <div class="feature">
      <h3>Discover new chairs</h3>
      <p>Explore a variety of chair designs and styles from around the world.</p>
    </div>
    <div class="feature">
      <h3>Connect with other chair lovers</h3>
      <p>Join a community of like-minded individuals who share your passion for chairs.</p>
    </div>
    <div class="feature">
      <h3>Show off your collection</h3>
      <p>Share photos of your favorite chairs and get feedback from other members.</p>
    </div>
  </div>
  
  <h2>Join Tables today</h2>
  <p>Sign up for Tables and start sharing your favorite chairs with the world.</p>
  <button>Join Tables</button>
</main>
  </body>

{% endblock %}

website/templates/landing.html
{% extends '_layout.html' %}

{% block body %}
  <div class="container my-5">
    <h1 class="display-4 mb-3">Welcome to Tables!</h1>
    <h3>Tables is a social media platform where users can ONLY post pictures of chairs. We believe that chairs are an underappreciated piece of furniture, and we want to give them the attention they deserve!</h3>
    <div class="row mt-4">
      <div class="col-md-6">
        <h2 class="mb-2">Why Chairs?</h2>
        <h4 class="mb-3">Chairs are essential to our daily lives. Whether you're sitting at a desk, having a meal, or just relaxing, chairs are always there to support you. Yet, how often do we stop to appreciate their design and functionality?</h4>
        <h4 class="mb-3">At Tables, we want to change that. By focusing solely on chairs, we hope to create a community that shares our love and appreciation for this humble yet indispensable piece of furniture.</h4>
      </div>
      <div class="col-md-6">
        <h2 class="mb-2">How It Works</h2>
        <h4 class="mb-3">Posting on Tables is easy! All you have to do is upload a picture of a chair, give it a title, and then hit submit.</h4>
        <h4 class="mb-3">If your post contains a chair, it will be visible on our feed for other users to see and like. Make sure to also leave comments and likes on other users' posts!</h4>
        <h4 class="mb-3">So what are you waiting for? Join the Tables community today and start sharing your love of chairs!</h4>
      </div>
      <div class="mt-5">
        <h3>Make sure to NOT to post images of Tables!</h3>
        <a class="btn btn-primary" href="/signup">Join Today!</a>
      </div>
    </div>
  </div>
{% endblock %}